using System;
using System.Windows.Controls;

namespace Rapid.Panels
{
    /// <summary>
    /// Interaction logic for ThreadPanel.xaml
    /// </summary>
    public partial class ThreadPanel : Grid
	{
		public ThreadPanel()
		{
            try
            {
                this.InitializeComponent();
                init();
            }
            catch (Exception ex)
            { RWrapper.RW_MainInterface.MYINSTANCE().WriteErrorLog("FrontEndError:TH01", ex); }
		}
        void init()
        {
            try
            {
                txtThreadCount.Minimum = 2;
                txtThreadCount.Maximum = 15;
            }
            catch (Exception ex)
            { RWrapper.RW_MainInterface.MYINSTANCE().WriteErrorLog("FrontEndError:TH02", ex); }
        }

		private void dgvThreadProperties_AutoGeneratedColumns(object sender, System.EventArgs e)
		{
            try
            {
                for (int i = 0; i < dgvThreadProperties.Columns.Count; i++)
                    dgvThreadProperties.Columns[i].Width = new DataGridLength(1, DataGridLengthUnitType.Star);
            }
            catch (Exception ex)
            { RWrapper.RW_MainInterface.MYINSTANCE().WriteErrorLog("FrontEndError:TH03", ex); }
		}

		private void RootSurfaceFlatChbk_Click(object sender, System.Windows.RoutedEventArgs e)
		{			
            try
            {
                RWrapper.RW_Thread.MYINSTANCE().UpdateThreadCountChange((int)txtThreadCount.Value, (bool)TopSurfaceFlatChbk.IsChecked, (bool)RootSurfaceFlatChbk.IsChecked);
            }
            catch (Exception ex)
            { RWrapper.RW_MainInterface.MYINSTANCE().WriteErrorLog("FrontEndError:TH04", ex); }
		}

		private void TopSurfaceFlatChbk_Click(object sender, System.Windows.RoutedEventArgs e)
		{
			// TODO: Add event handler implementation here.
            try
            {
                RWrapper.RW_Thread.MYINSTANCE().UpdateThreadCountChange((int)txtThreadCount.Value, (bool)TopSurfaceFlatChbk.IsChecked, (bool)RootSurfaceFlatChbk.IsChecked);
            }
            catch (Exception ex)
            { RWrapper.RW_MainInterface.MYINSTANCE().WriteErrorLog("FrontEndError:TH05", ex); }
		}
	}
}