using System;
using System.Windows.Controls;

namespace Rapid.Utilities
{
    /// <summary>
    /// Interaction logic for RAxisRecordPanel.xaml
    /// </summary>
    public partial class RAxisRecordPanel : Grid
	{
		public RAxisRecordPanel()
		{
			this.InitializeComponent();
            this.dgvValues.AutoGeneratedColumns += new EventHandler(dgvValues_AutoGeneratedColumns);
		}

        void dgvValues_AutoGeneratedColumns(object sender, EventArgs e)
        {
            try
            {
                dgvValues.Columns[0].Width = new DataGridLength(0.5, DataGridLengthUnitType.Star);
                dgvValues.Columns[1].Width = new DataGridLength(0.3, DataGridLengthUnitType.Star);
                dgvValues.Columns[2].Width = new DataGridLength(0.2, DataGridLengthUnitType.Star);
                dgvValues.UpdateLayout();
                dgvValues.ScrollIntoView(dgvValues.Items[dgvValues.Items.Count - 1], dgvValues.Columns[0]);
            }
            catch (Exception)
            { }
        }
	}
}